admin:
  auth:
    disable-checks: false
    iap-gke-jwt: true
    iap-appengine-jwt: false
    bearer-token: false

  db:
    initialize-on-start: false
    upgrade-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/${ADMIN_DATABASE_NAME}
    username:
    password:

  tanagra-core:
    base-path: https://tanagra-test.api.verily.com
    oauth-client-id: 730051649108-uepfa779jvl5ct2u7thfkqje5gda0ona.apps.googleusercontent.com
    use-adc: true

logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: tanagra-vumc-admin
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
      static-locations: classpath:/api/